# Generated by Django 5.2.3 on 2025-06-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
