# Generated by Django 5.2.3 on 2025-06-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_todolist_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='datetime',
            new_name='datetime_start',
        ),
    ]
