# Generated by Django 5.2.3 on 2025-06-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_rename_datetime_todolist_datetime_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
