# Generated by Django 5.2.3 on 2025-06-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_todolist_datetime_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='situation',
            field=models.BooleanField(default=False),
        ),
    ]
