# Generated by Django 5.2.3 on 2025-07-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0006_alter_todolist_description_alter_todolist_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todolist',
            new_name='Task',
        ),
    ]
